name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run lint
        working-directory: ./frontend
        run: npx eslint .
      
      - name: Build app
        working-directory: ./frontend
        run: npm run build
    
